FROM node:18-alpine

WORKDIR /app

# Copiar os arquivos de dependência
COPY package*.json ./
RUN npm install

# Copiar o resto do código
COPY . .

# Expor a porta que o servidor usa
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["node", "index.js"]